# Generated by Django 2.2.6 on 2020-03-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0002_auto_20200303_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
